version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
#    networks:
#      - custom
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_fastapi
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: user123
    ports:
      - 5050:80
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

#networks:
#  custom:
#    driver: bridge
