version: '3.8'
services:
  backend:
    container_name: backend_fastapi
    build:
      context: .
      dockerfile: ./docker/fastapi/DockerFile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    env_file:
      - ./src/.env
    depends_on:
      - db
      - redis

  worker:
    container_name: worker_fastapi
    build:
      context: .
      dockerfile: ./docker/fastapi/DockerFile
    command: bash -c "celery -A tasks.tasks.celery worker --loglevel=INFO"
    volumes:
      - ./src:/app
    env_file:
      - ./src/.env
    depends_on:
      - redis

  flower:
    container_name: flower_fastapi
    build:
      context: .
      dockerfile: ./docker/fastapi/DockerFile
    command: bash -c "celery --broker=redis://redis_fastapi:6379/0 flower --port=5555"
    ports:
      - "5555:5555"
    volumes:
      - ./src:/app
    env_file:
      - ./src/.env
    depends_on:
      - redis
      - worker

  db:
    container_name: db_fastapi
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    env_file:
      - ./src/.env

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_fastapi
    env_file:
      - ./src/.env
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  redis:
    container_name: redis_fastapi
    image: redis:7
    ports:
      - "6379:6379"
