version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_fastapi
    env_file:
      - .env
    ports:
      - 5050:80
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: radis_fastapi
    command: redis-server --requirepass red1s100500
    ports:
      - 6379:6379
