FROM python:3.8-slim

WORKDIR /app

EXPOSE 8000

COPY ./src/requirements.txt /app/requirements.txt

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

RUN pip install -r requirements.txt \
    && rm -rf /root/.cache/pip


#COPY ./src/ /app/